please check
MementoMoriSchoolProject/FrontEnd-Funeral pull request #17
Opened 2020-11-22 17:59 UTC by robinburenhva

appointments

2020-11-22 18:43 UTC, ZIggyVeerman commented on src/pages/create/creation-framework.tsx
> +        title: 'APpointment',
Typo: APpointment

2020-11-22 18:45 UTC, ZIggyVeerman commented on src/pages/forms/appointment/query/get-appointment.ts
> +export const useGetAppointments = () => useQuery(GET_APPOINTMENTS, {  });
you should add the types back in

2020-11-22 18:45 UTC, ZIggyVeerman commented on src/pages/forms/appointment/mutation/save-appointment.ts
> +export const useSaveAppointments = () => useMutation(SAVE_APPOINTMENTS);
you should add the types back in

2020-11-22 18:46 UTC, ZIggyVeerman requested changes
Changes should be made comments added, Also all checks fail for the circleCI maybe check what is happening there.

2021-01-11 12:53 UTC, joeypothoff approved these changes
Looks good to me.

2021-01-11 13:44 UTC, ZIggyVeerman approved these changes

2021-01-11 13:44 UTC, merged